New module: Seqera Platform CLI (#2151)
* New module: seqera-cli

* [automated] Update CHANGELOG.md

* Add barplot, version, parse uncompressed

* Fix

* Update docs

* Support custom header["to_float"] function, use it for duration. Meaninful colors for barplot

* Shorter repo name

* remove mention of table sorting

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Robert Syme <rob.syme@gmail.com>

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Robert Syme <rob.syme@gmail.com>

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Phil Ewels <phil.ewels@seqera.io>

* Remove to_float, support format callable instead. Add humanize for dates and gb

* nbsp

* Fix

* Address review, fixes

* Add nextflow and platform versions, use color badges, use deterministic hash for categorical Bscale

* Fix lint

* Fix order

* Rename search pattern

* Add simple barplots

* Simple barplots: show if no data

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Harshil Patel <drpatelh@users.noreply.github.com>

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Harshil Patel <drpatelh@users.noreply.github.com>

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Harshil Patel <drpatelh@users.noreply.github.com>

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Harshil Patel <drpatelh@users.noreply.github.com>

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Harshil Patel <drpatelh@users.noreply.github.com>

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Harshil Patel <drpatelh@users.noreply.github.com>

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Harshil Patel <drpatelh@users.noreply.github.com>

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Harshil Patel <drpatelh@users.noreply.github.com>

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Harshil Patel <drpatelh@users.noreply.github.com>

* Update multiqc/modules/seqera_cli/seqera_cli.py

Co-authored-by: Harshil Patel <drpatelh@users.noreply.github.com>

---------

Co-authored-by: MultiQC Bot <multiqc-bot@seqera.io>
Co-authored-by: Phil Ewels <phil.ewels@seqera.io>
Co-authored-by: Robert Syme <rob.syme@gmail.com>
Co-authored-by: Harshil Patel <drpatelh@users.noreply.github.com>

diff --git a/.github/workflows/multiqc.yml b/.github/workflows/multiqc.yml
--- a/.github/workflows/multiqc.yml
+++ b/.github/workflows/multiqc.yml
@@ -99,7 +99,7 @@ jobs:
         run: |
           multiqc ${{ needs.changes.outputs.single_module }} test_data/data/modules/ --filename all_ignored.html --ignore-samples '*'
           if [[ -f all_ignored.html ]]; then
-            echo "No report should have been generated! Likely due to a module missing self.ignore_samples() or UserWarning when no matching files are found" >&2
+            echo "No report should have been generated! Likely due to a module missing self.ignore_samples() or ModuleNoSamplesFound when no matching files are found" >&2
             exit 1
           fi
 
